version: '3.6'

services:
    packagist:
        build:
            context: .
        image: okvpn/packeton:latest
        container_name: packagist
        hostname: packagist
        environment:
            ADMIN_USER: admin
            ADMIN_PASSWORD: 123456
            ADMIN_EMAIL: admin@example.com
        ports:
            - '127.0.0.1:8088:80'
        volumes:
            - .docker:/data
