version: '3.6'

services:
    packagist:
        build:
            context: .
        image: okvpn/packeton:latest
        container_name: packagist
        hostname: packagist
        environment:
            PRIVATE_REPO_DOMAIN_LIST: bitbucket.org gitlab.com github.com
        ports:
            - '127.0.0.1:8088:80'
