name: Build docker images

on:
  push:
    tags: ["v*"]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Calculate docker image tag
        id: set-tag
        uses: docker/metadata-action@master
        with:
          images: packeton/packeton
          flavor: |
            latest=false
          tags: |
            type=raw,value=latest,enable=${{ github.ref == 'refs/heads/master' }}
            type=pep440,pattern={{major}}.{{minor}}
      
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: "${{ steps.set-tag.outputs.tags }}"
          file: "Dockerfile"
