name: "Run Tests"

on:
  push:
    paths:
      - 'src/**'
      - 'tests/**'
      - 'templates/**'
      - 'config/**'
    branches:
      - master
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

env:
  APP_ENV: test

jobs:
  tests:
    strategy:
      fail-fast: false
      matrix:
        redis: 6
        include:
          - php: '8.1'
#          - php: '8.2'
#            redis: '7'
          - php: '8.3'
            redis: '7'
            symfony: '7.0.*'
    name: PHP ${{ matrix.php }} SYMFONY ${{ matrix.symfony }}
    runs-on: ubuntu-20.04

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v3"
      
      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          coverage: "none"
          extensions: "curl, pdo, pdo_sqlite, sqlite, zip, redis"
          php-version: ${{ matrix.php }}
          tools: composer

      - name: "Install dependencies"
        run: |
          if [[ ! -z "${{ matrix.symfony }}" ]]; then
            export SYMFONY_REQUIRE="${{ matrix.symfony }}"
            echo "Install for $SYMFONY_REQUIRE"
            composer update --ansi --no-interaction
          else
            composer install --ansi --no-interaction
          fi
      - name: Start Redis
        uses: "supercharge/redis-github-action@1.6.0"
        with:
          redis-version: ${{ matrix.redis }}

      - name: "Run tests"
        run: "composer tests"
