name: "Run Tests"

on:
  push:
    paths:
      - 'src/**'
      - 'tests/**'
      - 'templates/**'
      - 'config/**'
    branches:
      - master
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

env:
  APP_ENV: test

jobs:
  tests:
    strategy:
      fail-fast: false
      matrix:
        include:
          - php: '8.1'
            driver: 'sqlite'
            redis: 6
          - php: '8.3'
            driver: 'pgsql'
            redis: 7
            symfony: '7.0.*'
    name: PHP ${{ matrix.php }} - ${{ matrix.driver }} SF ${{ matrix.symfony }}
    runs-on: ubuntu-20.04

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v3"
      
      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          coverage: "none"
          extensions: "curl, pdo, pdo_sqlite, pdo_mysql, pdo_pgsql, sqlite, zip, redis"
          php-version: ${{ matrix.php }}
          tools: composer

      - name: "Install Postgres"
        if: ${{ matrix.driver=='pgsql' }}
        uses: harmon758/postgresql-action@v1
        with:
          postgresql version: '14'

      - name: "Install dependencies"
#         temporary workaround to support Symfony 7.0 in tests.
        run: |
          set -x
          if [[ ! -z "${{ matrix.symfony }}" ]]; then
            export SYMFONY_REQUIRE="${{ matrix.symfony }}"

            composer config --global --auth http-basic.demo.packeton.org token ${{ secrets.PACKETON_TOKEN }}
            composer config repositories.sf7 composer https://demo.packeton.org/sf7

            composer update --ansi --no-interaction
          else
            composer install --ansi --no-interaction
          fi
      - name: Start Redis
        uses: "supercharge/redis-github-action@1.6.0"
        with:
          redis-version: ${{ matrix.redis }}

      - name: "Run tests"
        run: "composer tests"
